Scores/kommt und lasst uns christum ehren/reger, max
nun-singet-und-seid-froh/nun-singet-und-seid-froh pull request #17
Opened 2019-11-18 18:53 UTC by jonathan-scholbach

2019-11-19 20:34 UTC, fibsifan requested changes
You mixed changes to the template with changes to Music. I made some corrections to the music directly, but what do we do with the template?

2019-11-19 20:34 UTC, fibsifan commented on templates/SATTB/SATTB/modern/score.ly
> +        \set Staff.instrumentName = "tenor II"
Why the capitalization change in the template?

2019-11-19 20:34 UTC, fibsifan commented on templates/SATTB/SATTB/modern/score.ly
> +        \set Staff.instrumentName = "tenor I"
Capitalization

2019-11-19 20:34 UTC, fibsifan commented on templates/SATTB/SATTB/modern/score.ly
> +      \new Voice = "tenII" { global \tenIIVoice }
Oops

2019-11-21 23:30 UTC, jonathan-scholbach commented on templates/SATTB/SATTB/modern/score.ly
> +        \set Staff.instrumentName = "tenor II"
You are right, this is just a typo

2019-11-24 10:35 UTC, fibsifan requested changes
please remove the leftover conflict marker.

2019-11-24 10:35 UTC, fibsifan commented on scores/Kommt_und_lasst_uns_Christum_ehren/Kommt_und_lasst_uns_Christum_ehren_(Reger,_Max)/score.ly
> +<<<<<<< HEAD
Leftover conflict marker.

Tipp: `git diff --check`

2019-11-25 22:22 UTC, fibsifan approved these changes

2019-12-01 20:51 UTC, merged